import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Theme from "@/components/Theme";
import { ThemeProvider } from "@/components/theme-provider";
import "@radix-ui/themes/styles.css";
import { Theme as T } from "@radix-ui/themes";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <T>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="absolute top-10 right-10">
              <Theme />
            </div>
            {children}
          </ThemeProvider>
        </T>
      </body>
    </html>
  );
}
